# Generated by Django 5.0 on 2023-12-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Emailaddress',
            new_name='email',
        ),
    ]
